import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Provider from '@/context/AuthContext';
import ReactQueryProvider from '../context/ReactQueryProvider';
import ToasterContext from '@/context/ToasterContext';
import { ThemeProvider } from '@/context/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Job Search | Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <ReactQueryProvider>
            <Provider>
              <ToasterContext />
              {children}
            </Provider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
